-- P01 我的卡呼：完整資料表基準（可重複執行）
create table if not exists public."TblP01Question" (
  "QID" bigint generated by default as identity primary key,
  "Q" text not null,
  "CA" text not null,
  "WA1" text not null,
  "WA2" text not null,
  "WA3" text not null,
  "QCatMain" text not null default '未分類',
  "QCat" text not null default '未分類',
  "IsActive" boolean not null default true,
  "CreatedAt" timestamptz not null default now()
);

create table if not exists public."TblP01GameSession" (
  "GameID" bigint generated by default as identity primary key,
  "GameCode" text not null,
  "HostUserID" text not null,
  "QCat" text,
  "SelectedQCats" text not null default '[]',
  "CurrentQuestionNo" integer not null default 0,
  "CurrentQID" bigint references public."TblP01Question"("QID") on delete set null,
  "StartedAt" timestamptz,
  "EndedAt" timestamptz,
  "Status" text not null default 'waiting',
  "CreatedAt" timestamptz not null default now(),
  constraint "TblP01GameSession_Status_check" check ("Status" in ('waiting','playing','ended'))
);

create table if not exists public."TblP01GamePlayer" (
  "PlayerID" bigint generated by default as identity primary key,
  "GameID" bigint not null references public."TblP01GameSession"("GameID") on delete cascade,
  "UserID" text not null,
  "CorrectCount" integer not null default 0,
  "AnsweredCount" integer not null default 0,
  "TotalScore" integer not null default 0,
  "CreatedAt" timestamptz not null default now()
);

create table if not exists public."TblP01Attempt" (
  "AttemptID" bigint generated by default as identity primary key,
  "GameID" bigint not null references public."TblP01GameSession"("GameID") on delete cascade,
  "GameCode" text not null,
  "QID" bigint not null references public."TblP01Question"("QID") on delete restrict,
  "UserID" text not null,
  "Selected" text not null,
  "IsCorrect" boolean not null,
  "QCat" text,
  "ResponseTime" integer not null default 0,
  "Score" integer not null default 0,
  "CreatedAt" timestamptz not null default now()
);
